# Generated by Django 4.1.7 on 2023-03-31 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comm', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Subcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comm', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.article')),
                ('commentrep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.login')),
            ],
        ),
    ]
