# Generated by Django 4.1.7 on 2023-03-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0004_comment_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='forkey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.login'),
        ),
    ]
