# Generated by Django 4.1.7 on 2023-04-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0005_article_forkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='forkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.login'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('forkey', 'title')},
        ),
    ]
