# Generated by Django 4.1.7 on 2023-04-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0008_alter_article_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='forkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.login'),
            preserve_default=False,
        ),
    ]
