# Generated by Django 4.1.7 on 2023-04-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0012_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.login'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='commentrep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.comment'),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.login'),
        ),
    ]
