# Generated by Django 4.1.7 on 2023-04-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0013_alter_comment_user_alter_subcomment_commentrep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=30)),
                ('phone_number', models.CharField(max_length=255)),
                ('password', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
    ]
