# Generated by Django 4.1.7 on 2023-04-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleApp', '0014_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ArticleApp.signup'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
